name: social_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  # State management
  flutter_bloc: ^8.1.2
  # Create diverse designs like WhatsApp and Telegram.
  flutter_chat_bubble: ^2.0.2
  # To add staggered animations to your ListView, GridView
  flutter_staggered_animations: ^1.1.1
  # Purify dart code
  dartz: ^0.10.1
  # Implement value based equality
  equatable: ^2.0.5
  # Simple direct Service Locator that allows to access the concrete implementation from everywhere
  get_it: ^7.6.0
  # A Flutter package to use fonts from fonts.google.com.
  image_picker: ^0.8.7+1
  # For date/number formatting and parsing
  intl: ^0.17.0
  # Flutter plugin for reading and writing simple key-value pairs for cache
  shared_preferences: ^2.0.20
  # Dart library that checks for internet
  internet_connection_checker: ^1.0.0+1
  # A collection of loading indicators animated with flutter
  loading_indicator: ^3.1.1
  # Updating app's launcher icon
  flutter_launcher_icons: ^0.13.1
  # Flutter plugin for displaying inline video
  video_player: ^2.8.1
  # Easily create toast messages
  fluttertoast: ^8.2.4
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.0
  # To load and cache network images
  cached_network_image: ^3.3.0
  # For splash screen
  flutter_native_splash: ^2.3.9
  # Animated Bottom Navigation Bar Widget
  animated_bottom_navigation_bar: ^1.3.0
  # Customizable animated page indicator
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900

  assets:
    - assets/
    - assets/images/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
